# Task 1 :

1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    x = 5 / 0
except ZeroDivisionError:
    print("Error dividing by zero")

Error dividing by zero


2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [2]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(sub+" "+verb+" "+obj)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

1 . Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [4]:
import numpy as np
def AlexandreTheophile(lst1,N,increasing):
    if(increasing==False):
        print(np.column_stack([[x**(N-1-i)  for x in lst1 ]for i in range(N)]))
    else:     
        print(np.column_stack([[x**i for x in lst1 ]for i in range(N) ]))
        
        

lst=[1,2,3,4]
n=len(lst)
print("when increasing boolean is True:",)
AlexandreTheophile(lst,n,increasing=True)
print("...........")
print("when increasing boolean is false:")
AlexandreTheophile(lst,n,increasing=False)     

when increasing boolean is True:
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
...........
when increasing boolean is false:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Note: we can also use np.vander() ethod generate this matice